#!/bin/sh

. /etc/rc.subr

name=sftp_watchd
rcvar=sftp_watchd_enable

load_rc_config $name
sftp_watchd_enable=${sftp_watchd_enable:-"NO"}


command="/usr/sbin/${name}"
pidfile="/var/run/$name.pid"
required_files="/usr/sbin/${name}"

extra_commands="status"
start_cmd="sftp_watchd_start"
stop_cmd="sftp_watchd_stop"
restart_cmd="sftp_watchd_restart"
status_cmd="sftp_watchd_status"


sftp_watchd_start() {
	echo "Starting sftp_watchd."
	unlink /dev/log
    ln -s /home/sftp/dev/log /dev/log
	/usr/sbin/daemon  -f -p "${pidfile}" "${command}"
}
sftp_watchd_stop() {
	echo Kill: `test -e $pidfile && cat $pidfile`
	if [ -e $pidfile ] ; then
		pid=`cat $pidfile`
		kill $pid
	fi
}
sftp_watchd_restart() {
	sftp_watchd_stop
	sftp_watchd_start
}
sftp_watchd_status() {
	pid=`cat $pidfile`
	echo "sftp_watchd is running as pid $pid."
}


run_rc_command "$1"